language: go
sudo: false
go:
  - 1.8.3

install:
  - go get -u github.com/golang/dep/cmd/dep

script:
  - echo $GOPATH
  - make ci-build-twitter-daemon
  - make ci-build-twitter-daemon-mipsle
  - make ci-build-tweet-fail
  - make ci-build-tweet-success
