language: go
sudo: false

go:
  - 1.8.3

services:
  - docker

install:
  - go get -u github.com/golang/dep/cmd/dep

script:
  - echo $GOPATH
  - make ci-build-twitter-daemon
  - make ci-build-twitter-daemon-mipsle
  - make ci-build-tweet-fail
  - make ci-build-tweet-success
  - docker build -t denismakogon/detect-task -f serverless/detect-task/Dockerfile serverless/detect-task
  - docker build -t denismakogon/tweet-fail -f serverless/tweet-fail/Dockerfile serverless/tweet-fail
  - docker build -t denismakogon/tweet-success -f serverless/tweet-success/Dockerfile serverless/tweet-success
