language: go
sudo: false

go:
  - 1.8.3

services:
  - docker

install:
  - go get -u github.com/golang/dep/cmd/dep

script:
  - make ci-build-twitter-daemon
  - make ci-build-twitter-daemon-mipsle
  - make ci-build-tweet-fail
  - make ci-build-tweet-success
